version: '3.8'

networks:
  monitor:
    driver: bridge

volumes:
  grafana: {}
  influxdb: {}

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - monitor
    restart: always
